---
- hosts: localhost
  connection: local
  gather_facts: yes
  any_errors_fatal: yes

- include_vars: secrets.yml

# Taken from https://github.com/bonovoxly/playbook/tree/master/old_format/awsbackup

  tasks:
    - name: Default snapshots are 7 unless defined.
      set_fact:
        COUNT: "{{ default count }}"
      when: COUNT is not defined

    - name: Verify incremental type (daily, weekly, monthly).
      fail:
        msg: "INCREMENTAL is not defined. Allowed parameters are daily, weekly, monthly. Exiting."
      when: INCREMENTAL is not defined or INCREMENTAL != 'Daily' and INCREMENTAL != 'Weekly' and INCREMENTAL != 'Monthly'

    - name: Gather EC2 facts.
      ec2_remote_facts:
        aws_access_key: "{{ aws_snapshot_accesskey }}"
        aws_secret_key: "{{ aws_snapshot_secretkey }}"
        region: us-east-1
        filters:
          "tag:Backup": "{{ INCREMENTAL }}"
      register: ec2_facts

    - name: Print facts.
      debug:
        msg: "{{ ec2_facts }}"

    - name: Snapshot Instances.
      ec2_snapshot:
        aws_access_key: "{{ aws_snapshot_accesskey }}"
        aws_secret_key: "{{ aws_snapshot_secretkey }}"
        region: us-east-1
        instance_id: "{{ item.id }}"
        device_name: "{{ item.root_device_name }}"
        description: "Automatic scheduled snapshot taken on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}."
        snapshot_tags:
          Name: "{{ item.tags.Name }}_{{ INCREMENTAL }}_{{ ansible_date_time.date }}."
          Identifier: autosnap
          Instance: "{{ item.tags.Name }}"
          Incremental: "{{ INCREMENTAL }}"
          Department: "{{ item.tags.Department }}"
      with_items: "{{ ec2_facts.instances }}"


    - name: Find snapshots.
      ec2_snapshot_facts:
        aws_access_key: "{{ aws_snapshot_accesskey }}"
        aws_secret_key: "{{ aws_snapshot_secretkey }}"
        region: us-east-1
        filters:
          "tag:identifier": "autosnap"
          "tag:incremental": "{{ INCREMENTAL }}"
      register: ec2_snapshot_facts

    - name: Print snapshot facts
      debug:
        msg: "{{ ec2_snapshot_facts }}"

    - name: Get ordered list of snapshots for each instance.
      set_fact:
        snaps_fact_list:  "{{ ec2_snapshot_facts.snapshots|selectattr('tags.identifier', 'equalto', 'autosnap')|selectattr('tags.incremental', 'equalto', INCREMENTAL)|selectattr('tags.instance', 'equalto', item.tags.Name)|sort(attribute='start_time')|reverse|map(attribute='id')|list }}"
      with_items: ec2_facts.instances
      register: snaps_fact_list_register

    - name: Debug ordered list of snapshots.
      debug:
        msg: "{{ snaps_fact_list_register.results }}"

    - name: Cut the list by our COUNT variable.
      set_fact:
        snaps_cut: "{{ item.ansible_facts['snaps_fact_list'][COUNT:] }}"
      with_items: snaps_fact_list_register.results
      register: snaps_cut_register

    - name: Debug cut list.
      debug:
        msg: "{{ item.ansible_facts.snaps_cut }}"
      with_items: snaps_cut_register.results

    - name: Create empty list for joins.
      set_fact:
        snaps_joined: "[]"

    - name: Join the nested list of snapshots that will be deleted.
      set_fact:
        snaps_joined: "{{ snaps_joined }} + {{ item.ansible_facts.snaps_cut }}"
      with_items: snaps_cut_register.results
      register: snaps_joined_register

    - name: Debug another joined list.
      debug:
        msg: "{{ snaps_joined }}"

    - name: Delete snapshots in the nested list of snapshots.
      ec2_snapshot:
        aws_access_key: "{{ aws_snapshot_accesskey }}"
        aws_secret_key: "{{ aws_snapshot_secretkey }}"
        region: us-east-1
        state: absent
        snapshot_id: "{{ item }}"
      with_items: snaps_joined
      register: deleted_snapshots

    - name: Debug snapshots that were deleted.
      debug:
        msg: "{{ item.item }}"
      with_items: deleted_snapshots.results